# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "szfuqwn-wj11528"
user = "paulburden"
authenticator = "snowflake"
password = "mypassword"
## role = "HOL_ROLE"
## warehouse = "HOL_WH"
database = "test_streamlit"
schema = "test_sch"

[szfuqwn-wj11528]
account = "szfuqwn-wj11528"
user = "paulburden"
authenticator = "snowflake"
database = "test_streamlit"
schema = "test_sch"